In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('./data/train.csv')
df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [21]:
df = df.drop(['id'], axis=1)

In [23]:
df

keyword location                                               text  \
0        NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1        NaN      NaN             Forest fire near La Ronge Sask. Canada   
2        NaN      NaN  All residents asked to 'shelter in place' are ...   
3        NaN      NaN  13,000 people receive #wildfires evacuation or...   
4        NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   
...      ...      ...                                                ...   
7608     NaN      NaN  Two giant cranes holding a bridge collapse int...   
7609     NaN      NaN  @aria_ahrary @TheTawniest The out of control w...   
7610     NaN      NaN  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...   
7611     NaN      NaN  Police investigating after an e-bike collided ...   
7612     NaN      NaN  The Latest: More Homes Razed by Northern Calif...   

      target  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
7608       1  
7609       1  
7610       1  
7611       1  
7612       1  

[7613 rows x 4 columns]

In [40]:
df.loc[60:70, ['keyword', 'text']]

keyword                                               text
60    ablaze  Revel in yours wmv videos by means of mac fare...
61    ablaze  Progressive greetings!\n\nIn about a month stu...
62    ablaze  Rene Ablaze &amp; Jacinta - Secret 2k13 (Falle...
63    ablaze  @Navista7 Steve these fires out here are somet...
64    ablaze  #NowPlaying: Rene Ablaze &amp; Ian Buff - Magn...
65    ablaze  @nxwestmidlands huge fire at Wholesale markets...
66    ablaze  @ablaze what time does your talk go until? I d...
67  accident  'I can't have kids cuz I got in a bicycle acci...
68  accident  Accident on I-24 W #NashvilleTraffic. Traffic ...
69  accident  Accident center lane blocked in #SantaClara on...
70  accident  http://t.co/GKYe6gjTk5 Had a #personalinjury a...

In [42]:
import nltk

In [43]:
from pytorch_pretrained_bert import BertModel, BertTokenizer

In [46]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [50]:
w = tokenizer.convert_tokens_to_ids(['hello', 'world'])

In [51]:
bertmodel = BertModel.from_pretrained('bert-base-uncased')

In [55]:
import torch
torch.tensor(w)

tensor([7592, 2088])

In [57]:
bertmodel(torch.tensor(w).view(1, -1)).size()

([tensor([[[ 0.2342,  0.4187, -0.3626,  ..., -0.1554, -0.3838, -0.0074],
           [ 0.6342,  1.1416,  1.0819,  ..., -0.2009, -0.0843, -0.5864]]],
         grad_fn=<AddBackward0>),
  tensor([[[ 0.4153,  0.0188, -0.2105,  ...,  0.0493, -0.1618, -0.1698],
           [ 0.7684,  1.9880,  1.1199,  ..., -0.7275, -0.1263, -0.7111]]],
         grad_fn=<AddBackward0>),
  tensor([[[-0.2007,  0.2708,  0.0075,  ...,  0.2475, -0.0257,  0.0119],
           [ 0.7127,  2.0042,  0.7233,  ...,  0.0373, -0.2503, -0.0933]]],
         grad_fn=<AddBackward0>),
  tensor([[[-0.2711, -0.0598, -0.1825,  ..., -0.5826, -0.1346,  0.1213],
           [ 0.5141,  1.9654,  0.3506,  ..., -0.3855, -0.2491,  0.3105]]],
         grad_fn=<AddBackward0>),
  tensor([[[-0.0699,  0.9620, -0.2964,  ..., -1.1470, -0.2573,  0.3411],
           [ 0.4215,  2.2552,  0.5336,  ..., -0.6305, -0.5313, -0.3380]]],
         grad_fn=<AddBackward0>),
  tensor([[[-0.1245,  0.5391,  0.3720,  ...,  0.0806, -0.0871,  0.3962],
           [-0.09

In [58]:
torch.tensor(w).view(1, -1)

tensor([[7592, 2088]])

In [65]:
text = 'I am Mr. Huderson. Nice to meet you!'

In [66]:
tokenizer.tokenize(text)

['i',
 'am',
 'mr',
 '.',
 'hu',
 '##ders',
 '##on',
 '.',
 'nice',
 'to',
 'meet',
 'you',
 '!']

In [69]:
x = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(text))

In [68]:
bertmodel.eval()

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): BertLayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): BertLayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Lin

In [71]:
out, _ = bertmodel(torch.tensor(x).view(1, -1))
out

[tensor([[[ 1.9892e-02,  4.1328e-01, -2.2181e-01,  ...,  2.8706e-01,
            2.1810e-01,  1.2246e-01],
          [ 2.3839e-01,  1.5515e-01,  3.8293e-02,  ...,  3.2719e-01,
            1.8921e+00, -8.7180e-01],
          [ 6.5080e-01, -1.2168e-02,  6.3863e-01,  ..., -7.2215e-01,
            1.3916e+00,  5.7533e-01],
          ...,
          [ 3.7708e-02,  1.0109e+00, -4.7395e-01,  ...,  5.1558e-01,
           -1.1349e-01,  1.4388e-01],
          [-8.0848e-01,  9.0437e-01,  8.1153e-01,  ...,  8.5186e-01,
            4.6818e-01,  5.5948e-01],
          [ 4.4215e-01,  8.4447e-04, -2.4784e-01,  ...,  4.3650e-01,
            5.2623e-01,  8.9815e-01]]], grad_fn=<AddBackward0>),
 tensor([[[ 0.0931, -0.0026, -0.1744,  ...,  0.3635,  0.3804, -0.3315],
          [-0.0346, -0.0546, -0.1009,  ..., -0.0390,  2.1550, -1.1211],
          [ 0.7665,  0.3611,  0.6790,  ..., -0.9274,  2.0904,  0.3948],
          ...,
          [ 0.2872,  1.4756,  0.3939,  ...,  0.0975, -0.2599, -0.4322],
          [-0

In [72]:
x

[1045, 2572, 2720, 1012, 15876, 13375, 2239, 1012, 3835, 2000, 3113, 2017, 999]

In [74]:
len(out)

12

In [75]:
text = "Who was Jim Henson ? Jim Henson was a puppeteer"
tokenized_text = tokenizer.tokenize(text)

In [76]:
tokenized_text

['who',
 'was',
 'jim',
 'henson',
 '?',
 'jim',
 'henson',
 'was',
 'a',
 'puppet',
 '##eer']

In [77]:
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
indexed_tokens

[2040, 2001, 3958, 27227, 1029, 3958, 27227, 2001, 1037, 13997, 11510]

In [79]:
tokens_tensor = torch.tensor(indexed_tokens)

In [80]:
model = BertModel.from_pretrained('bert-base-uncased')
model.eval()

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [81]:


# Predict hidden states features for each layer
encoded_layers, _ = model(tokens_tensor.view(1, -1))
len(encoded_layers)

12

In [82]:
encoded_layers[0].size()

torch.Size([1, 11, 768])

In [83]:
for text in df.head().text:
    print(text)

Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all
Forest fire near La Ronge Sask. Canada
All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected
13,000 people receive #wildfires evacuation orders in California 
Just got sent this photo from Ruby #Alaska as smoke from #wildfires pours into a school 


In [84]:
a = [1, 2, 3, 5, 6]
import numpy as np

In [85]:
np.random.shuffle(a)

In [86]:
a

[2, 5, 1, 3, 6]

In [87]:
b = [2, 4, 6, 8, 1]

In [88]:
list(zip(a, b))

[(2, 2), (5, 4), (1, 6), (3, 8), (6, 1)]